version: "3.8"
services:
    database:
        image: mysql:8.0.27
        ports:
            - 3306:3306
        restart: always
        volumes:
            - ./mysql/data:/var/lib/mysql
            # - ./mysql/sql/:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456

    web:
        build: ./www
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - "database"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.0
        ports:
            - 8888:80
        restart: always
        environment:
            - PMA_HOST=database
        depends_on:
            - "database"
